# Generated by Django 6.0.4 on 2026-04-25 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialMultimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Material')),
                ('tipo', models.CharField(choices=[('pdf', 'Partitura / PDF'), ('video', 'Video de Práctica'), ('link', 'Enlace Externo (YouTube/Drive)')], max_length=10)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='multimedia/', verbose_name='Archivo Físico')),
                ('link_externo', models.URLField(blank=True, null=True, verbose_name='URL / Enlace')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('profesor', models.ForeignKey(limit_choices_to={'rol': 'profesor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
