# Generated by Django 6.0.4 on 2026-04-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banda_academia', '0002_examen_pregunta_opcion_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='duracion_minutos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
