# Generated by Django 6.0.4 on 2026-04-26 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banda_academia', '0003_alter_examen_duracion_minutos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='activa',
        ),
        migrations.RemoveField(
            model_name='examen',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='examen',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='examen',
            name='duracion_minutos',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='examen',
            name='fecha_inicio',
            field=models.DateTimeField(),
        ),
    ]
