# Generated by Django 6.0.4 on 2026-04-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banda_academia', '0004_remove_examen_activa_remove_examen_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('multiple', 'Selección Múltiple'), ('vf', 'Verdadero o Falso')], default='multiple', max_length=20),
        ),
        migrations.AlterField(
            model_name='opcion',
            name='texto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='puntos',
            field=models.PositiveIntegerField(default=1, help_text='Puntaje de esta pregunta'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='texto',
            field=models.TextField(verbose_name='Enunciado de la pregunta'),
        ),
    ]
