# Generated by Django 6.0.4 on 2026-04-26 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banda_academia', '0005_pregunta_tipo_alter_opcion_texto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='puntos',
            field=models.PositiveIntegerField(default=1, help_text='Puntaje entre 1 y 20', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
