# Generated by Django 6.0.4 on 2026-04-26 19:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banda_academia', '0006_alter_pregunta_puntos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resultado',
            new_name='ResultadoExamen',
        ),
    ]
