# Generated by Django 6.0.4 on 2026-04-26 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banda_academia', '0007_rename_resultado_resultadoexamen'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion_seleccionada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banda_academia.opcion')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banda_academia.pregunta')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='banda_academia.resultadoexamen')),
            ],
        ),
    ]
