# Generated by Django 6.0.4 on 2026-04-27 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banda_academia', '0008_respuestaestudiante'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('trompeta', 'Trompeta'), ('bombo', 'Bombo'), ('redoblante', 'Redoblante'), ('lira', 'Lira')], max_length=50)),
                ('codigo_interno', models.CharField(max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('mantenimiento', 'Mantenimiento')], default='activo', max_length=20)),
                ('estudiante_asignado', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instrumento_propio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
