# Generated by Django 6.0.4 on 2026-04-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banda_academia', '0009_instrumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumento',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('mantenimiento', 'En Mantenimiento')], default='activo', max_length=20),
        ),
    ]
